# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        arch: ["x64", "x86"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: ${{ matrix.arch }}
    
    - name: Setup Node.js
      run: |
        npm init -y
        npm install -g node-gyp

    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.12

    - name: Check validity
      run: |
        whereis make
        ls
        
    - name: Build
      run: |
        node-gyp configure
        ls
        ls build
        node-gyp build
        ls
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: UnsafeJS-${{matrix.arch}}-Node${{matrix.node-version}}-Build
        path: ./**/*.node
